### ISSUE TITLE
Profiles list?

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/guard13007.com#25]
If so, here's the Galcon one: https://www.galcon.com/profile/view.php?name=guard13007

**Comment by boomchacle** [comment]
that would be cool

**Comment by TangentFoxy** [comment]
Along with profiles, listing referral links for places would be cool, such as this one for DigitalOcean: https://m.do.co/c/56eb47f4ae99

**Comment by TangentFoxy** [comment]
Partially implemented in that I listed my last.fm on contact, but this is far from ideal.

**Comment by TangentFoxy** [comment]
referral links https://www.rescuetime.com/ref/457239

https://www.rescuetime.com/get_rescuetime

**Comment by TangentFoxy** [comment]
Done(ish) on dev.

@boomchacle If you want to see the work in progress / new style I will be bringing to my site soon.. -> https://dev.guard13007.com/contact/profiles
