### ISSUE TITLE
guard13007.com/submit - Planes to Review!

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/guard13007.com#32]
```
guard13007.com/submit - Planes to Review!

Craft name,
 id,
 download link (NEEDS TO BE A URL AND VERIFIED SOMEHOW),
 description,
 mods used,
 YOUR name,
 KSP version,
 status (automatically set, and I can modify),
 action groups,
 episode (video id, used for embed),
 rejection reason (used if I reject a plane),
 picture (NEEDS TO BE A URL AND VERIFIED SOMEHOW)

Status options:
- unseen 0, default
- pending 1, when I have seen that you submitted it and it is queued for review
- reviewed 2, when I have reviewed it, I set the episode field as well
- rejected 3, when I reject a plane for some reason
```

**Comment by TangentFoxy** [comment]
Consider public setting / download setting instead of defaulting to public.

**Comment by TangentFoxy** [comment]
Consider adding accounts.

**Comment by TangentFoxy** [comment]
ADD NOCAPTCHA SUPPORT

**Comment by TangentFoxy** [comment]
ToDo:
- [ ] NoCaptcha Support
- [ ] Styling
- [ ] Administration
- [ ] Testing pagination
- [ ] Individual pages display
- [ ] URL validation

**Comment by TangentFoxy** [comment]
NoCaptcha stuff
- http://webdesign.tutsplus.com/tutorials/how-to-integrate-no-captcha-recaptcha-in-your-website--cms-23024
- https://www.google.com/recaptcha/admin#site/321219314?setup

**Comment by TangentFoxy** [comment]
imgur API https://api.imgur.com/

**Comment by TangentFoxy** [comment]
ref markdown processing: http://www.frykholm.se/files/markdown.lua

**Comment by boomchacle** [comment]
I think that when on one craft page, you should have the option to go to the next page and previous without going to the craft list.

**Comment by TangentFoxy** [comment]
_I think_ That's a lot easier said than done, but I'll think about it and see if I can do that.
