### ISSUE TITLE
Update tutoring hours

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/guard13007.com#6]
- [x] Now able to work
- [x] Ask @Lomeli12 if he is as well...
- [x] And what are his Wednesday hours?

**Comment by Lomeli12** [comment]
New hours:
Mon: 11am-2pm (walk in)
Tues: 9am-12pm (appointment)
Thurs: 9am-12pm (appointment)
Fri: 11am-2pm (walk in)
