### ISSUE TITLE
Add search to KSP submissions

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/guard13007.com#92]
Basic partial string matching, sort order by craft name matches, followed by creator name matches, followed by description matches. Do not match action groups/versions/etc.

Potentially also allow sorting results with tablesort? Also, it'd be nice to have other sorts besides the default maybe?

**Comment by boomchacle** [comment]
I think that it would be a good idea

**Comment by TangentFoxy** [comment]
This has been partially implemented at https://guard13007.com/ksp/search

Right now, it only does partial string matches for craft names. It also doesn't have a specified order, so it's probably returning them in submission order...which I am fine with and am choosing to keep if that is so.

To do: Also search by creator name, description, KSP version, and mods used. KSP version search as a separate search field from the regular search, that shows versions in the results instead of just craft by creator.

**Comment by TangentFoxy** [comment]
- [x] Also make it display a message when no search results are found (use @session.info with a redirect to a blank search).
- [x] And make the results table use the same table structure as craft listing!

**Comment by TangentFoxy** [comment]
Okay, this is complete! :D
